# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Npm Publish Package

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: echo "Deploying ${{ github.ref_name }} version publicly"
      - run: |
          version=$(echo "${{ github.ref_name }}" | grep -oP '^v?\K([0-9]+\.[0-9]+\.[0-9]+)$')
          if [ -n "$version" ]; then
            yarn publish --access public --new-version "$version"
          else
            echo "Invalid version format: ${{ github.ref_name }}"
            exit 1
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}
